import type { Result } from "@atlas/shared";
import type { ClaimCheckResult } from "./verifier.port";

/**
 * A single checklist item from the deterministic critic (Phase 6, P6.1).
 *
 * Each item is a binary pass/fail check that can be evaluated without AI.
 */
export interface CriticCheckItem {
  /** Stable check id for programmatic handling. */
  readonly id: string;
  /** Human-readable check name. */
  readonly name: string;
  /** The check category. */
  readonly category: CriticCheckCategory;
  /** Whether the check passed. */
  readonly passed: boolean;
  /** Human-readable detail (pass reason or failure explanation). */
  readonly detail: string;
}

/** Categories of deterministic critic checks. */
export type CriticCheckCategory =
  | "path-exists"
  | "plan-coverage"
  | "contract-satisfied"
  | "verification-match"
  | "completeness";

/**
 * Input for the deterministic critic checklist.
 */
export interface CriticCheckInput {
  /** The model's answer text. */
  readonly answer: string;
  /** File paths cited in the answer. */
  readonly citedPaths: readonly string[];
  /** Plan step targets the answer should address. */
  readonly planTargets: readonly string[];
  /** Claim check results from verification. */
  readonly claimResults: ClaimCheckResult;
  /** Output contract assertions that should be satisfied. */
  readonly outputContract?: readonly OutputContractCheck[];
}

/** An assertion about the output shape. */
export interface OutputContractCheck {
  /** What to check (e.g. "contains-function", "no-errors"). */
  readonly kind: string;
  /** The expected value. */
  readonly value: string;
}

/**
 * The result of the deterministic critic checklist.
 */
export interface CriticCheckResult {
  /** All checklist items evaluated. */
  readonly items: readonly CriticCheckItem[];
  /** How many checks passed. */
  readonly passed: number;
  /** How many checks failed. */
  readonly failed: number;
  /** True when all checks passed. */
  readonly allPassed: boolean;
  /** Overall verdict. */
  readonly verdict: CriticVerdict;
}

/** The overall critic verdict. */
export type CriticVerdict = "pass" | "fail" | "partial";

/**
 * The AI critic's structured review (Phase 6, P6.1).
 *
 * Generated by calling the model with the answer + checklist results.
 */
export interface CriticReview {
  /** Issues found by the AI reviewer. */
  readonly issues: readonly CriticIssue[];
  /** Overall assessment. */
  readonly assessment: string;
  /** Whether a revision is recommended. */
  readonly revisionRecommended: boolean;
  /** Specific revision suggestions (empty when not recommended). */
  readonly suggestions: readonly string[];
}

/**
 * A single issue found by the AI reviewer.
 */
export interface CriticIssue {
  /** Issue severity. */
  readonly severity: "error" | "warning" | "info";
  /** What the issue is about. */
  readonly category: string;
  /** Human-readable description. */
  readonly description: string;
  /** Related file path (if applicable). */
  readonly filePath?: string;
}

/**
 * The critic configuration (Phase 6, P6.2).
 */
export interface CriticConfig {
  /**
   * Which model to use for the AI critic review.
   * - "same": use the same model that generated the answer
   * - "stronger": use a stronger/different model
   * - "none": skip AI critic, only run deterministic checks
   */
  readonly model: "same" | "stronger" | "none";
  /** Maximum revisions allowed after critic feedback (≤1 per plan). */
  readonly maxRevisions: number;
}

/**
 * Critic port (Phase 6, ADR-019).
 *
 * Two-phase review:
 * 1. Deterministic checklist (no AI, fast, catches structural issues)
 * 2. AI review (optional, catches semantic/logical issues)
 */
export interface CriticPort {
  /**
   * Run the deterministic checklist against an answer.
   *
   * Pure, no AI, no IO. Checks cited paths exist, plan coverage,
   * contract satisfaction, and verification claim alignment.
   */
  check(input: CriticCheckInput): CriticCheckResult;

  /**
   * Run the AI critic review (optional, requires provider).
   *
   * Takes the answer + deterministic checklist results and produces
   * a structured review with issues and revision suggestions.
   */
  review(
    answer: string,
    checklistResult: CriticCheckResult,
    contextSummary: string,
  ): Promise<Result<CriticReview>>;
}
